### ISSUE TITLE
@extend errors with grid

### ISSUE THREAD

**Issue by alexovit** [KyleKing/Customizable-Bootstrap-Stylus#7]
Got errors while using grid mixins. Any ideas about solving?
main.styl:

```
@import "lib/custom.bootstrap.styl"

header
  .brand
    make-sm-column(3)
```

result:

```
   While building the application:
   error: Stylus compiler error: client/stylesheets/main.styl:undefined

   Failed to @extend "$col-float-xs"
```

Also this one:
main.styl:

```
@import "lib/custom.bootstrap.import.styl"
header
  make-row()
```

result:

```
   error: Stylus compiler error: client/stylesheets/main.styl:14

   Failed to @extend ".clearfix"
```

**Comment by KyleKing** [comment]
Thanks for posting an issue. I started [this folder](https://github.com/KyleKing/Customizable-Bootstrap-Stylus/tree/master/tests/Extends) to test out a solution. I wasn't able to replicate the error with make-sm-column(3), but saw the same error for make-row(). I'm working on it now and will post more if I can figure it out
- What does your Custom.bootstrap.json file look like?

**Comment by alexovit** [comment]
`make-sm-column(3)` works if I `@import "lib/custom.bootstrap.import.styl"` instead of `@import "lib/custom.bootstrap.styl"` so probably that is just a non proper import.

In `custom.bootstrap.json` everything was true. 

```
{
    "modules" : {
        "variables": true,
        "mixins": true,

        "normalize": true,
        "print": true,
        "glyphicons": true,

        "scaffolding": true,
        "utilities": true,
        "type": true,
        "code": true,
        "grid": true,
        "tables": true,
        "forms": true,
        "buttons": true,

        "component-animations": true,
        "dropdowns": true,
        "button-groups": true,
        "input-groups": true,
        "navs": true,
        "navbar": true,
        "breadcrumbs": true,
        "pagination": true,
        "pager": true,
        "labels": true,
        "badges": true,
        "jumbotron": true,
        "thumbnails": true,
        "alerts": true,
        "progress-bars": true,
        "media": true,
        "list-group": true,
        "panels": true,
        "responsive-embed": true,
        "wells": true,
        "close": true,

        "modals": true,
        "tooltip": true,
        "popovers": true,
        "carousel": true,

        "responsive-utilities": true
    }
}
```

**Comment by KyleKing** [comment]
Thanks!

Yeah, the `@import "lib/custom.bootstrap.import.styl"` is the proper one because it pulls in the user-editable file and mixins.

To help make the documentation better, where did you see the `@import "lib/custom.bootstrap.styl"` or was it automatically generated?

**Comment by alexovit** [comment]
Nowhere. After seeing an error I was just thinking that I could mess up with imports trying different. Probably it will be nice to clarify it in documentation with something like:

# Mixins

You can import bootstrap mixins in your stylus file using `@import "custom.bootstrap.import.styl"`

**Comment by KyleKing** [comment]
Haha, I will definitely make the change. For anything we figure out here, I'll update the readme. Let me know what to improve!

I thought I figured out the issue, but no luck yet. I'm working on making some changes to the data package and the load order of the final files

**Comment by KyleKing** [comment]
I think I found the issue. I was missing a utility file in the mixins import along with other errors. So kudos for bringing this error up!

I'm going to be busy tonight, but I'm going to try to push the update tomorrow morning.

UPDATE:
Actually just went ahead and pushed the update to Atmosphere. I tested it within an app I'm working on and the above cases you mentioned worked (I had to delete and retype any whitespace) along with some other mixins I tested.

Let me know if it is fixed! Or if you see any other issues.

**Comment by KyleKing** [comment]
Actually just went ahead and pushed the update to Atmosphere. I tested it within an app I'm working on and the above cases you mentioned worked (I had to delete and retype any whitespace) along with some other mixins I tested.

Let me know if it is fixed! Or if you see any other issues.

**Comment by alexovit** [comment]
Problem solved. Thank you for fast response. I will report in case of any other problems, just started the project.
